In [8]:
list1 = [1,3,5,7]
print (list1)

[1, 3, 5, 7]


In [9]:
import numpy as np # loading a library 

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
# One dimensional array 
# two dimenstional array ----defined as creating two dimensional arrays 
array1 = np.array(list1)
print (array1)

[1 3 5 7]


In [12]:
array2 = np.array([1,3,5,7])
print (array2)
array2.ndim

[1 3 5 7]


1

In [13]:
print("creating 2 dimensional array -- create two array only ")
print('--' * 30)

array3 = np.array([[1,3,5,7] , [2,4,6,8]])
print(array3)

print('--' * 30)

print("checking array formular")

array3.ndim


creating 2 dimensional array -- create two array only 
------------------------------------------------------------
[[1 3 5 7]
 [2 4 6 8]]
------------------------------------------------------------
checking array formular


2

In [14]:
import numpy as np # loading a library 
#create a 3 dimensional arrays ---two dimenstional array and Two Dimenstional array 

print("creating 3 dimensional array -- create two array and two arrays ")
print('--' * 30)

array4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print (array4)

print('--' * 30)
array4.ndim # check the number of array 



creating 3 dimensional array -- create two array and two arrays 
------------------------------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------------------------------------------------------


3

In [18]:
#check the shape of the array 
# shape --Give the number of object you have in an array 
array3.shape




(2, 4)

In [19]:
print(array3)

[[1 3 5 7]
 [2 4 6 8]]


In [25]:
array4.shape



(2, 2, 2)

In [21]:
print(array4)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
print(array1)

[1 3 5 7]


In [26]:
print(array2)

[1 3 5 7]


In [ ]:
array1 + array2

[ 2  6 10 14]


In [ ]:
# check the data type of the array 
print(array1.dtype)

int64
